# Generated by Django 2.0.7 on 2018-09-25 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, help_text='Name of price offer', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='productprice',
            old_name='cost',
            new_name='value',
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='Internal facing reference to product', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.ProductPriceGroup'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='priority',
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('price_group', 'product')},
        ),
    ]
