# Generated by Django 2.0.7 on 2018-09-24 21:20
from dateutil import parser
from django.db import migrations


def create_prices(apps, schema_migration):
    ProductPrice = apps.get_model('products.ProductPrice')
    Product = apps.get_model('products.Product')
    ProductPriceGroup = apps.get_model('products.ProductPriceGroup')
    p1_bf_gr = ProductPriceGroup.objects.create(name='Black FRIDAY',
                                                date_start=parser.parse('Nov 23, 2018'),
                                                date_end=parser.parse('Nov 25, 2018'))
    p2_2019y = ProductPriceGroup.objects.create(name='2019 Prices',
                                                date_start=parser.parse('Jan 01, 2019'),
                                                date_end=parser.parse('Dec 31, 2019'))
    try:
        products = (Product.objects.get(code='big_widget'), Product.objects.get(code='sm_widget'))
        all_prices = []
        for price_group, prices in zip((p1_bf_gr, p2_2019y), ((800, 0), (1200, 125))):
            for price, product in zip(prices, products):
                all_prices.append(ProductPrice(value=price, product=product, price_group=price_group))
        ProductPrice.objects.bulk_create(all_prices)
    except Product.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180925_1112'),
    ]

    operations = [
        migrations.RunPython(code=create_prices, reverse_code=migrations.RunPython.noop)
    ]
